name: Matrix Build Demo (a20bf30)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Matrix - Node ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14, 16, 18]  # ✅ three variants
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: matrix-a20bf30
        run: echo "Building for Node.js version ${{ matrix.version }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Generate build artifact
        run: |
          echo "Build artifact for Node.js version ${{ matrix.version }}" > build-info.txt
          echo "Timestamp: $(date)" >> build-info.txt
          node -v >> build-info.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-a20bf30-v${{ matrix.version }}
          path: build-info.txt
