name: Matrix Build with Artifact Management

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  matrix-build:
    name: Build (${{ matrix.os }}, Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16, 18, 20]
        include:
          - os: ubuntu-latest
            suffix: linux
          - os: macos-latest
            suffix: macos
          - os: windows-latest
            suffix: windows
      fail-fast: false
      max-parallel: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: matrix-a20bf30
        run: |
          echo "Matrix build identifier: a20bf30"
          echo "Building on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"
          echo "Platform: ${{ runner.os }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Generate build artifact
        run: |
          # Create a unique build artifact with meaningful content
          cat > build-output-${{ matrix.suffix }}-v${{ matrix.node-version }}.json << EOF
          {
            "buildId": "a20bf30",
            "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "platform": "${{ matrix.os }}",
            "nodeVersion": "${{ matrix.node-version }}",
            "runnerOs": "${{ runner.os }}",
            "artifactType": "matrix-build-demo",
            "checksum": "$(date +%s | sha256sum | head -c 8)"
          }
          EOF
          
          # Create additional build files
          echo "Build completed successfully for ${{ matrix.os }} - Node ${{ matrix.node-version }}" > build-status.txt
          echo "Build configuration:" >> build-status.txt
          echo "- OS: ${{ matrix.os }}" >> build-status.txt
          echo "- Node.js: ${{ matrix.node-version }}" >> build-status.txt
          echo "- Runner: ${{ runner.os }}" >> build-status.txt
          echo "- Workflow: ${{ github.run_id }}" >> build-status.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-a20bf30-${{ matrix.suffix }}-node${{ matrix.node-version }}
          path: |
            build-output-${{ matrix.suffix }}-v${{ matrix.node-version }}.json
            build-status.txt
          retention-days: 7

      - name: Verify artifact content
        run: |
          echo "Verifying generated artifacts..."
          cat build-output-${{ matrix.suffix }}-v${{ matrix.node-version }}.json
          echo ""
          cat build-status.txt
          echo ""
          # Verify files are non-empty
          if [ ! -s "build-output-${{ matrix.suffix }}-v${{ matrix.node-version }}.json" ]; then
            echo "ERROR: JSON artifact is empty!"
            exit 1
          fi
          if [ ! -s "build-status.txt" ]; then
            echo "ERROR: Status file is empty!"
            exit 1
          fi
          echo "✅ All artifacts contain valid content"

  post-build:
    name: Post-Build Summary
    runs-on: ubuntu-latest
    needs: matrix-build
    if: always()
    
    steps:
      - name: matrix-a20bf30-summary
        run: |
          echo "Matrix build a20bf30 completed"
          echo "Total matrix jobs: 9"
          echo "OS variants: ubuntu-latest, macos-latest, windows-latest"
          echo "Node.js variants: 16, 18, 20"
          echo "Artifact prefix: build-a20bf30-"
